INSERT INTO Courses VALUES ('CSE100', 'Data Structures', 3, '0');
INSERT INTO Courses VALUES ('CSE101', 'Algorithms', 4, '1');
INSERT INTO Courses VALUES ('CSE102', 'Operating Systems', 3, '2');
INSERT INTO Courses VALUES ('CSE103', 'Database Systems', 4, '3');
INSERT INTO Courses VALUES ('CSE104', 'Computer Networks', 3, '4');
INSERT INTO Courses VALUES ('CSE105', 'Artificial Intelligence', 4, '5');
INSERT INTO Courses VALUES ('CSE106', 'Machine Learning', 3, '6');
INSERT INTO Courses VALUES ('CSE107', 'Cybersecurity', 4, '7');
INSERT INTO Courses VALUES ('CSE108', 'Cloud Computing', 3, '8');
INSERT INTO Courses VALUES ('CSE109', 'Web Development', 4, '9');
INSERT INTO Courses VALUES ('CSE110', 'Software Engineering', 3, '10');
INSERT INTO Courses VALUES ('CSE111', 'Embedded Systems', 4, '11');
INSERT INTO Courses VALUES ('CSE112', 'Digital Logic Design', 3, '12');
INSERT INTO Courses VALUES ('CSE113', 'Computer Architecture', 4, '13');
INSERT INTO Courses VALUES ('CSE114', 'Human-Computer Interaction', 3, '14');
INSERT INTO Courses VALUES ('CSE115', 'Game Development', 4, '15');
INSERT INTO Courses VALUES ('CSE116', 'Big Data Analytics', 3, '16');
INSERT INTO Courses VALUES ('CSE117', 'Blockchain Technology', 4, '17');
INSERT INTO Courses VALUES ('CSE118', 'Internet of Things', 3, '18');
INSERT INTO Courses VALUES ('CSE119', 'Quantum Computing', 4, '19');
INSERT INTO Courses VALUES ('CSE120', 'Augmented Reality', 3, '20');
INSERT INTO Courses VALUES ('CSE121', 'Virtual Reality', 4, '21');
INSERT INTO Courses VALUES ('CSE122', 'Natural Language Processing', 3, '22');
INSERT INTO Courses VALUES ('CSE123', 'Computational Biology', 4, '23');
INSERT INTO Courses VALUES ('CSE124', 'Mobile App Development', 3, '24');
INSERT INTO Courses VALUES ('CSE125', 'Distributed Systems', 4, '25');
INSERT INTO Courses VALUES ('CSE126', 'Computer Vision', 3, '26');
INSERT INTO Courses VALUES ('CSE127', 'Parallel Computing', 4, '27');
INSERT INTO Courses VALUES ('CSE128', 'High-Performance Computing', 3, '28');
INSERT INTO Courses VALUES ('CSE129', 'Wireless Networks', 4, '29');
INSERT INTO Courses VALUES ('CSE130', 'Cryptography', 3, '30');
INSERT INTO Courses VALUES ('CSE131', 'Ethical Hacking', 4, '31');
INSERT INTO Courses VALUES ('CSE132', 'Computer Graphics', 3, '32');
INSERT INTO Courses VALUES ('CSE133', 'Neural Networks', 4, '33');
INSERT INTO Courses VALUES ('CSE134', 'Edge Computing', 3, '34');
INSERT INTO Courses VALUES ('CSE135', 'Robotics', 4, '35');
INSERT INTO Courses VALUES ('CSE136', 'Automation Systems', 3, '36');
INSERT INTO Courses VALUES ('CSE137', 'Control Systems', 4, '37');
INSERT INTO Courses VALUES ('CSE138', 'Embedded AI', 3, '38');
INSERT INTO Courses VALUES ('CSE139', 'Signal Processing', 4, '39');
INSERT INTO Courses VALUES ('CSE140', 'Bioinformatics', 3, '40');
INSERT INTO Courses VALUES ('CSE141', 'Semantic Web', 4, '41');
INSERT INTO Courses VALUES ('CSE142', 'Compiler Design', 3, '42');
INSERT INTO Courses VALUES ('CSE143', 'Theory of Computation', 4, '43');
INSERT INTO Courses VALUES ('CSE144', 'Mathematical Logic', 3, '44');
INSERT INTO Courses VALUES ('CSE145', 'Cloud Security', 4, '45');
INSERT INTO Courses VALUES ('CSE146', 'DevOps', 3, '46');
INSERT INTO Courses VALUES ('CSE147', 'Software Testing', 4, '47');
INSERT INTO Courses VALUES ('CSE148', 'Digital Image Processing', 3, '48');
INSERT INTO Courses VALUES ('CSE149', 'Advanced Databases', 4, '49');