INSERT INTO Courses VALUES ('CS101', 'Introduction to Computer Science', 3, 1, 10);
INSERT INTO Courses VALUES ('MATH201', 'Calculus I', 4, 2, 20);
INSERT INTO Courses VALUES ('PHYS101', 'Physics Fundamentals', 3, 3, 30);
INSERT INTO Courses VALUES ('ENG101', 'English Composition', 3, 4, 40);
INSERT INTO Courses VALUES ('HIST210', 'World History', 3, 5, 50);
INSERT INTO Courses VALUES ('BIO101', 'Introduction to Biology', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM101', 'General Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('ECON201', 'Microeconomics', 3, 8, 80);
INSERT INTO Courses VALUES ('MATH202', 'Calculus II', 4, 2, 20);
INSERT INTO Courses VALUES ('CS201', 'Data Structures', 3, 1, 10);
INSERT INTO Courses VALUES ('ART101', 'Art History', 3, 9, 90);
INSERT INTO Courses VALUES ('CS301', 'Algorithms', 3, 1, 10);
INSERT INTO Courses VALUES ('PHYS201', 'Electricity and Magnetism', 4, 3, 30);
INSERT INTO Courses VALUES ('MATH301', 'Linear Algebra', 3, 2, 20);
INSERT INTO Courses VALUES ('ENG201', 'Advanced English', 3, 4, 40);
INSERT INTO Courses VALUES ('CHEM201', 'Organic Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('BIO201', 'Genetics', 4, 6, 60);
INSERT INTO Courses VALUES ('CS401', 'Operating Systems', 3, 1, 10);
INSERT INTO Courses VALUES ('MATH402', 'Differential Equations', 4, 2, 20);
INSERT INTO Courses VALUES ('ECON301', 'Macroeconomics', 3, 8, 80);
INSERT INTO Courses VALUES ('PHYS301', 'Quantum Mechanics', 4, 3, 30);
INSERT INTO Courses VALUES ('CS501', 'Artificial Intelligence', 3, 1, 10);
INSERT INTO Courses VALUES ('ENG301', 'Literature Analysis', 3, 4, 40);
INSERT INTO Courses VALUES ('MATH501', 'Abstract Algebra', 4, 2, 20);
INSERT INTO Courses VALUES ('BIO301', 'Cell Biology', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM301', 'Inorganic Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('HIST301', 'Modern History', 3, 5, 50);
INSERT INTO Courses VALUES ('MATH601', 'Probability and Statistics', 3, 2, 20);
INSERT INTO Courses VALUES ('CS601', 'Machine Learning', 3, 1, 10);
INSERT INTO Courses VALUES ('PHYS401', 'Thermodynamics', 3, 3, 30);
INSERT INTO Courses VALUES ('ECON401', 'International Economics', 3, 8, 80);
INSERT INTO Courses VALUES ('BIO401', 'Biochemistry', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM401', 'Physical Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('CS701', 'Cloud Computing', 3, 1, 10);
INSERT INTO Courses VALUES ('MATH701', 'Numerical Methods', 4, 2, 20);
INSERT INTO Courses VALUES ('PHYS501', 'Astrophysics', 3, 3, 30);
INSERT INTO Courses VALUES ('ENG401', 'Creative Writing', 3, 4, 40);
INSERT INTO Courses VALUES ('MATH801', 'Topology', 3, 2, 20);
INSERT INTO Courses VALUES ('BIO501', 'Microbiology', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM501', 'Analytical Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('HIST401', 'Ancient Civilizations', 3, 5, 50);
INSERT INTO Courses VALUES ('CS801', 'Blockchain Technology', 3, 1, 10);
INSERT INTO Courses VALUES ('ECON501', 'Behavioral Economics', 3, 8, 80);
INSERT INTO Courses VALUES ('BIO601', 'Evolutionary Biology', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM601', 'Environmental Chemistry', 4, 7, 70);
INSERT INTO Courses VALUES ('PHYS601', 'Solid State Physics', 3, 3, 30);
INSERT INTO Courses VALUES ('CS901', 'Cybersecurity', 3, 1, 10);
INSERT INTO Courses VALUES ('MATH901', 'Mathematical Logic', 4, 2, 20);
INSERT INTO Courses VALUES ('BIO701', 'Biotechnology', 4, 6, 60);
INSERT INTO Courses VALUES ('ENG501', 'Professional Writing', 3, 4, 40);
INSERT INTO Courses VALUES ('HIST501', 'History of the Americas', 3, 5, 50);
INSERT INTO Courses VALUES ('CS1001', 'Intro to Data Science', 3, 1, 10);
INSERT INTO Courses VALUES ('ECON601', 'Development Economics', 3, 8, 80);
INSERT INTO Courses VALUES ('MATH1001', 'Real Analysis', 3, 2, 20);
INSERT INTO Courses VALUES ('BIO1001', 'Ecology', 4, 6, 60);
INSERT INTO Courses VALUES ('CHEM1001', 'General Laboratory Techniques', 4, 7, 70);
INSERT INTO Courses VALUES ('PHYS1001', 'Classical Mechanics', 3, 3, 30);
INSERT INTO Courses VALUES ('ENG1001', 'Public Speaking', 3, 4, 40);
INSERT INTO Courses VALUES ('HIST1001', 'History of Europe', 3, 5, 50);
INSERT INTO Courses VALUES ('CS1002', 'Web Development', 3, 1, 10);
INSERT INTO Courses VALUES ('ECON1002', 'Introduction to Global Trade', 3, 8, 80);
INSERT INTO Courses VALUES ('MATH1002', 'Discrete Mathematics', 3, 2, 20);
INSERT INTO Courses VALUES ('BIO1002', 'Human Anatomy', 4, 6, 60);